<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Registro_Lote extends Model
{
    public $timestamps = false;

    protected $table = 'registros_lote';

    protected $fillable = [
        // Common fields
        'lote',
        'data_fabricacao',
        'completed',
        
        // PAGINA 3
        'lote_agua_enriquecida',
        'id_usuario_lote_agua_enriquecida',
        'pressao_ar_comprimido',
        'pressao_H',
        'pressao_He_refrigeracao',
        'pressao_He_analitico',
        'radiacao_ambiental_lab',
        'id_usuario_verificacao_p3',
        'hora_inicio_irradiacao_agua_enriquecida',
        'hora_final_irradiacao_agua_enriquecida',
        'ativ_teorica_F18',
        'id_usuario_irradiacao_agua_enriquecida',
        'hora_inicio_transferir_F18_sintese',
        'hora_final_transferir_F18_sintese',
        'id_usuario_transferir_F18_sintese',
        'ocorrencias_p3',
        'ocorrencias_horario_p3',
        'id_usuario_ocorrencias_p3',
        'logbook_anexado',
        'logbook_data',
        'logbook_time',
        'id_usuario_logbook',
        
        // PAGINA 4
        'modulo_sintese',
        'kryptofix222_lote',
        'kryptofix222_data_validade',
        'triflato_manose_lote',
        'triflato_manose_data_validade',
        'hidroxido_sodio_lote',
        'hidroxido_sodio_data_validade',
        'agua_injetaveis_lote',
        'agua_injetaveis_data_validade',
        'acetronitrila_anidra_lote',
        'acetronitrila_anidra_data_validade',
        'ifp_synthera_lote',
        'ifp_synthera_data_validade',
        'sep_pak_lote',
        'sep_pak_data_validade',
        'coluna_scx_lote',
        'coluna_scx_data_validade',
        'coluna_c18_lote',
        'coluna_c18_data_validade',
        'coluna_alumina_lote',
        'coluna_alumina_data_validade',
        'seringa_3ml_lote',
        'seringa_3ml_data_validade',
        'agulha_05x25_lote',
        'agulha_05x25_data_validade',
        'agua_injetavel_seringa_lote',
        'agua_injetavel_seringa_data_validade',
        'etanol_seringa_lote',
        'etanol_seringa_data_validade',
        'NaHCO3_seringa_lote',
        'NaHCO3_seringa_data_validade',
        'id_usuario_separado_registrado_p4',
        'data_separado_registrado_p4',
        'id_usuario_recebido_conferido_p4',
        'data_recebido_conferido_p4',
        
        // PAGINA 5
        'hora_inicio_montagem_kit_synthera',
        'hora_final_montagem_kit_synthera',
        'id_usuario_execucao_montagem_kit_synthera',
        'id_usuario_verificacao_montagem_kit_synthera',
        'temperatura_lab_producao',
        'umidade_lab_producao',
        'id_usuario_verificacao_p5',
        'limpeza_celula',
        'verif_volume_H218O',
        'verif_frasco_rejeitos',
        'verif_bolsa_ar',
        'abrir_valvula_ar_comprimido',
        'abrir_valvula_nitrogenio',
        'verif_pos_capilares',
        'ligar_controle_synthera',
        'ligar_notebook_synthera',
        'iniciar_programa_mpb',
        'retirar_ifp_usado',
        'inserir_ifp_synthera',
        'conectar_theodorico',
        
        // PAGINA 6
        'iniciar_auto_teste',
        'efetuar_diluicao_triflato_manose',
        'remover_bloco_vermelho',
        'fechar_portas_bbs',
        'pressionar_start',
        'id_usuario_verificacao_acoes',
        'ativ_chegada_18F',
        'ativ_residual_18F',
        'ativ_modulo_sintese',
        'ativ_modulo_fracionamento',
        'hora_inicio_sintese',
        'hora_final_sintese',
        'rendimento_sintese',
        'id_usuario_execucao_p6',
        'id_usuario_verificacao_p6',
        'ocorrencias_p6',
        'ocorrencias_horario_p6',
        'id_usuario_execucao_ocorrencias_p6',
        'id_usuario_verificacao_ocorrencias_p6',
        
        // PAGINA 7
        'kit_fracionamento_1_lote',
        'kit_fracionamento_1_data_validade',
        'kit_fracionamento_2_lote',
        'kit_fracionamento_2_data_validade',
        'filtro_millex_gs_lote',
        'filtro_millex_gs_data_validade',
        'filtro_millex_gv_lote',
        'filtro_millex_gv_data_validade',
        'soro_fisiologico_lote',
        'soro_fisiologico_data_validade',
        'agulha_09x40_lote',
        'agulha_09x40_data_validade',
        'frascos_15ml_qtd',
        'frascos_15ml_lote',
        'frascos_15ml_data_validade',
        'frascos_bulk_lote',
        'frascos_bulk_data_validade',
        'id_usuario_separado_registrado_p7',
        'data_separado_registrado_p7',
        'id_usuario_recebido_conferido_p7',
        'data_recebido_conferido_p7',
        'ligar_theodorico',
        'colocar_castelo_chumbo_dws',
        'pressionar_botao_park',
        'pressionar_botao_pinch_open',
        'retirar_kit_usado',
        'realizar_limpeza_theodorico',
        'conectar_capilares_synthera_bulk',
        'conectar_kit_fracionamento_1',
        'fechar_bomba_peristaltica',
        
        // PAGINA 8
        'pressionar_botao_pinch_close',
        'conectar_kit_fracionamento_2',
        'prender_capilares_parede_theodorico',
        'conectar_filtros_millex_gs',
        'verificar_linhas_conectadas',
        'verificar_conexoes_capilares',
        'verificar_agulha_succao',
        'fechar_porta',
        'programar_fracionamento_software',
        'imprimir_etiqueta_frascos',
        'alimentar_antecamara_frascos',
        'marcar_posicao_frascos',
        'pressionar_botao_from_synt',
        'pressionar_botao_bulk_dilution',
        'pressionar_botao_start',
        'id_usuario_verificado_p8',
        'atividade_fdg_18f',
        'volume_soro_fisiologico',
        'imprimir_anexar_relatorio_producao',
        'hora_inicio_p8',
        'hora_final_p8',
        'id_usuario_fracionamento_executado',
        
        // PAGINA 9
        'ocorrencias_p9',
        'ocorrencias_horario_p9',
        'id_usuario_execucao_ocorrencias_p9',
        'id_usuario_verificacao_ocorrencias_p9',
        
        // PAGINA 10
        'embalagem_balde_qtd',
        'embalagem_balde_separado',
        'embalagem_balde_conferido',
        'embalagem_case_qtd',
        'embalagem_case_separado',
        'embalagem_case_conferido',
        'etiquetas_it_qtd',
        'etiquetas_it_separado',
        'etiquetas_it_conferido',
        'bulas_fdg_qtd',
        'bulas_fdg_separado',
        'bulas_fdg_conferido',
        'id_usuario_separado_embalagem_p10',
        'horario_separado_embalagem_p10',
        'id_usuario_conferido_embalagem_p10',
        'horario_conferido_embalagem_p10',
        'decl_exped_qtd',
        'decl_exped_separado',
        'decl_exped_conferido',
        'ficha_emerg_qtd',
        'ficha_emerg_separado',
        'ficha_emerg_conferido',
        'nota_fiscal_qtd',
        'nota_fiscal_separado',
        'nota_fiscal_conferido',
        'termo_doacao_qtd',
        'termo_doacao_separado',
        'termo_doacao_conferido',
        'ident_veiculo_qtd',
        'ident_veiculo_separado',
        'ident_veiculo_conferido',
        'form_tam_qtd',
        'form_tam_separado',
        'form_tam_conferido',
        'form_iata_qtd',
        'form_iata_separado',
        'form_iata_conferido',
        'id_usuario_separado_expedicao_p10',
        'horario_separado_expedicao_p10',
        'id_usuario_conferido_expedicao_p10',
        'horario_conferido_expedicao_p10',
        'horario_final_emb_exped',
        'id_usuario_execucao_p10',
        'id_usuario_verificacao_p10',
        'ocorrencias_p10',
        'ocorrencias_horario_p10',
        'id_usuario_execucao_ocorrencias_p10',
        'id_usuario_verificacao_ocorrencias_p10',
        
        // PAGINA 11
        'aspecto_resultado',
        'aspecto_data',
        'id_usuario_aspecto',
        'ph_1_resultado',
        'ph_1_data',
        'id_usuario_ph_1',
        'ph_2_resultado',
        'ph_2_data',
        'id_usuario_ph_2',
        'pureza_radionuclidica_1_resultado',
        'pureza_radionuclidica_1_data',
        'id_usuario_pureza_radionuclidica_1',
        'pureza_radionuclidica_2_resultado',
        'pureza_radionuclidica_2_data',
        'id_usuario_pureza_radionuclidica_2',
        'meia_vida_resultado',
        'meia_vida_data',
        'id_usuario_meia_vida',
        'solventes_resultado',
        'solventes_data',
        'id_usuario_solventes',
        'ocorrencias_p11',
        'id_usuario_verificacao_ocorrencias_p11',
        
        // PAGINA 12
        'pureza_radioquimica_a_codigo',
        'pureza_radioquimica_a_resultado',
        'pureza_radioquimica_a_data',
        'id_usuario_pureza_radioquimica_a',
        'pureza_radioquimica_b_resultado',
        'pureza_radioquimica_b_data',
        'id_usuario_pureza_radioquimica_b',
        'pureza_quimica_resultado',
        'pureza_quimica_data',
        'id_usuario_pureza_quimica',
        'ocorrencias_p12',
        'id_usuario_verificacao_ocorrencias_p12',
        'aprovacao_fisico_quimico',
        'data_aprovacao_fisico_quimico',
        'id_usuario_aprovacao_fisico_quimico',
        
        // PAGINA 13
        'endotoxinas_codigo',
        'endotoxinas_1_resultado',
        'endotoxinas_2_resultado',
        'endotoxinas_3_resultado',
        'endotoxinas_4_resultado',
        'endotoxinas_data',
        'id_usuario_endotoxinas',
        'codigo_calibracao_pts',
        'lote_cartucho_pts',
        'membrana_equipamento',
        'membrana_lote',
        'membrana_validade',
        'id_usuario_membrana',
        'pressao_teste_bolha_fornecida',
        'pressao_teste_bolha_obtida',
        'id_usuario_pressao_teste_bolha',
        'ocorrencias_p13',
        'id_usuario_verificacao_ocorrencias_p13',
        'aprovacao_microbiologico',
        'data_aprovacao_microbiologico',
        'id_usuario_aprovacao_microbiologico',
        
        // PAGINA 14
        'esterilidade_data_inicio_analise',
        'id_usuario_esterilidade',
        'esterilidade_codigo',
        'esterilidade_1_resultado',
        'esterilidade_1_data',
        'id_usuario_esterilidade_1',
        'esterilidade_2_resultado',
        'esterilidade_2_data',
        'id_usuario_esterilidade_2',
        'esterilidade_3_resultado',
        'esterilidade_3_data',
        'id_usuario_esterilidade_3',
        'ocorrencias_p14',
        'aprovacao_esterilidade',
        'data_aprovacao_esterilidade',
        'id_usuario_aprovacao_esterilidade',
        
        // PAGINA 15
        'id_usuario_supervisor_controle_qualidade',
        'atendimento_criterios',
        'aprovacao_lote',
        'id_usuario_resposavel_garantia_qualidade',
        'hora_emissao_laudo',
    ];
}
